---
- name: install build depends
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - openssl-devel
    - libyaml-devel
    - readline-devel
    - zlib-devel
    - libffi-devel
    - git
    - acl
  become: true
  tags:
    - rbenv

